#!/bin/bash
# setup.sh — detect opencode and tailscale, install a launchd agent that runs
# opencode's web server, and expose it over HTTPS via Tailscale Serve so it
# can be installed as a PWA from a phone.

set -euo pipefail

PLIST_NAME="io.github.pandeiro.pwa4opencode"
PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$PROJECT_DIR/pwa4opencode.env"
PLIST_PATH="$HOME/Library/LaunchAgents/$PLIST_NAME.plist"

OPENCODE_BIN="${OPENCODE_BIN:-}"
TAILSCALE_BIN="${TAILSCALE_BIN:-}"
OPENCODE_PORT="${OPENCODE_PORT:-4096}"
DRY_RUN=0

usage() {
    cat <<EOF
Usage: ./setup.sh [options]

  --opencode PATH    Path to the opencode binary (skips auto-detection)
  --tailscale PATH   Path to the tailscale CLI (skips auto-detection)
  --port N           Local port for opencode's server (default: 4096)
  --dry-run          Detect dependencies and write the env file only;
                     do not install the agent or configure Tailscale
  --help             Show this help
EOF
}

while [ $# -gt 0 ]; do
    case "$1" in
        --opencode) OPENCODE_BIN="$2"; shift 2 ;;
        --tailscale) TAILSCALE_BIN="$2"; shift 2 ;;
        --port) OPENCODE_PORT="$2"; shift 2 ;;
        --dry-run) DRY_RUN=1; shift ;;
        --help|-h) usage; exit 0 ;;
        *) echo "error: unknown option: $1" >&2; usage >&2; exit 1 ;;
    esac
done

# resolve_bin BIN VALUE CANDIDATE_DIRS...
# Print an absolute path for BIN: explicit VALUE, else PATH lookup, else the
# first executable match in CANDIDATE_DIRS. Empty output if not found.
resolve_bin() {
    local bin="$1" value="$2"; shift 2
    if [ -n "$value" ]; then
        printf '%s\n' "$value"
        return
    fi
    local found dir
    found="$(command -v "$bin" 2>/dev/null || true)"
    if [ -z "$found" ]; then
        for dir in "$@"; do
            dir="${dir/#\~/$HOME}"
            if [ -x "$dir/$bin" ]; then
                found="$dir/$bin"
                break
            fi
        done
    fi
    printf '%s\n' "$found"
}

# validate_bin PATH... — the binary must actually run, not merely exist.
validate_bin() {
    "$1" --version >/dev/null 2>&1 || "$1" version >/dev/null 2>&1
}

echo "==> Detecting dependencies"

OPENCODE_BIN="$(resolve_bin opencode "$OPENCODE_BIN" \
    ~/.opencode/bin /opt/homebrew/bin /usr/local/bin)"
TAILSCALE_BIN="$(resolve_bin tailscale "$TAILSCALE_BIN" \
    /usr/local/bin /opt/homebrew/bin /Applications/Tailscale.app/Contents/MacOS)"

if [ -z "$OPENCODE_BIN" ] || ! validate_bin "$OPENCODE_BIN"; then
    echo "error: could not find a working opencode binary." >&2
    echo "       Install it (curl -fsSL https://opencode.ai/install | bash) or pass its" >&2
    echo "       location explicitly: ./setup.sh --opencode /path/to/opencode" >&2
    exit 1
fi

if [ -n "$TAILSCALE_BIN" ] && ! validate_bin "$TAILSCALE_BIN"; then
    echo "warning: $TAILSCALE_BIN exists but does not run; continuing without Tailscale." >&2
    TAILSCALE_BIN=""
fi

if [ -z "$TAILSCALE_BIN" ]; then
    echo "warning: tailscale not found. The agent will still be installed, but you will" >&2
    echo "         need to run 'tailscale serve --bg --https=443 $OPENCODE_PORT' yourself." >&2
fi

echo "    opencode:  $OPENCODE_BIN"
if [ -n "$TAILSCALE_BIN" ]; then
    echo "    tailscale: $TAILSCALE_BIN"
fi
echo "    port:      $OPENCODE_PORT"

if [ -n "${OPENCODE_SERVER_PASSWORD:-}" ]; then
    echo "    auth:      OPENCODE_SERVER_PASSWORD is set (basic auth will be enabled)"
fi

echo "==> Writing $ENV_FILE"
{
    echo "# Generated by setup.sh. Safe to delete; rerun ./setup.sh to recreate."
    echo "OPENCODE_BIN=$(printf '%q' "$OPENCODE_BIN")"
    if [ -n "$TAILSCALE_BIN" ]; then
        echo "TAILSCALE_BIN=$(printf '%q' "$TAILSCALE_BIN")"
    fi
    echo "OPENCODE_PORT=$OPENCODE_PORT"
    if [ -n "${OPENCODE_SERVER_PASSWORD:-}" ]; then
        echo "OPENCODE_SERVER_PASSWORD=$(printf '%q' "$OPENCODE_SERVER_PASSWORD")"
    fi
} > "$ENV_FILE"
chmod 600 "$ENV_FILE"

if [ "$DRY_RUN" -eq 1 ]; then
    echo "==> Dry run: stopping here (agent not installed, Tailscale not configured)"
    exit 0
fi

echo "==> Installing launchd agent ($PLIST_NAME)"
cat <<EOF > "$PLIST_PATH"
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$PLIST_NAME</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$PROJECT_DIR/run.sh</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>ThrottleInterval</key>
    <integer>10</integer>
    <key>StandardOutPath</key>
    <string>$PROJECT_DIR/opencode.log</string>
    <key>StandardErrorPath</key>
    <string>$PROJECT_DIR/opencode.err.log</string>
    <key>WorkingDirectory</key>
    <string>$PROJECT_DIR</string>
</dict>
</plist>
EOF

launchctl bootout "gui/$(id -u)" "$PLIST_PATH" >/dev/null 2>&1 \
    || launchctl unload "$PLIST_PATH" >/dev/null 2>&1 \
    || true
launchctl bootstrap "gui/$(id -u)" "$PLIST_PATH" >/dev/null 2>&1 \
    || launchctl load "$PLIST_PATH"

echo "==> Waiting for opencode to come up on 127.0.0.1:$OPENCODE_PORT"
READY=0
for _ in $(seq 1 15); do
    if curl -sf -o /dev/null "http://127.0.0.1:$OPENCODE_PORT/"; then
        READY=1
        break
    fi
    sleep 1
done

if [ "$READY" -eq 1 ]; then
    echo "    opencode is up."
    echo "==> Verifying PWA installability"
    PWA_OK=1
    curl -sf -o /dev/null "http://127.0.0.1:$OPENCODE_PORT/site.webmanifest" || PWA_OK=0
    if [ "$PWA_OK" -eq 1 ]; then
        MANIFEST_ICON="$(curl -sf "http://127.0.0.1:$OPENCODE_PORT/site.webmanifest" \
            | grep -o '"src": *"[^"]*"' | head -1 | cut -d'"' -f4 || true)"
        if [ -n "$MANIFEST_ICON" ]; then
            curl -sf -o /dev/null "http://127.0.0.1:$OPENCODE_PORT$MANIFEST_ICON" || PWA_OK=0
        fi
    fi
    curl -sf -o /dev/null "http://127.0.0.1:$OPENCODE_PORT/apple-touch-icon-v3.png" || PWA_OK=0
    if [ "$PWA_OK" -eq 1 ]; then
        echo "    manifest and icons are being served."
    else
        echo "    warning: PWA manifest or icons did not respond as expected." >&2
        echo "             Home-screen install may not work with this opencode version." >&2
        echo "             See docs/ADR.md for background." >&2
    fi
else
    echo "    warning: opencode did not respond within 15s. Check $PROJECT_DIR/opencode.err.log" >&2
fi

if [ -n "$TAILSCALE_BIN" ]; then
    echo "==> Configuring Tailscale Serve (HTTPS :443 -> 127.0.0.1:$OPENCODE_PORT)"
    if "$TAILSCALE_BIN" serve --bg --https=443 "$OPENCODE_PORT"; then
        TAILNET_HOST="$("$TAILSCALE_BIN" status --json 2>/dev/null \
            | grep -o '"DNSName": *"[^"]*"' | head -1 | cut -d'"' -f4 | sed 's/\.$//' || true)"
        if [ -n "$TAILNET_HOST" ]; then
            echo ""
            echo "    https://$TAILNET_HOST"
            echo ""
        fi
    else
        echo "warning: 'tailscale serve' failed (is tailscaled running and are you logged in?)." >&2
        echo "         Configure it manually: $TAILSCALE_BIN serve --bg --https=443 $OPENCODE_PORT" >&2
    fi
fi

echo ""
echo "Done. On your phone, open the URL above in Chrome or Safari and choose"
echo "\"Add to Home Screen\" to install opencode as a PWA."
echo "Logs: $PROJECT_DIR/opencode.log / opencode.err.log"
